### ISSUE TITLE
Improve the keys of temporal configuration

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#187]
@rayidghani and I were discussing this this afternoon (August 22, 2017) about this set of keys in `temporal_configuration`

```
        temporal_config:
          beginning_of_time: '2010-01-04' # earliest date included in features
          modeling_start_time: '2014-01-01' # earliest date in any model
          modeling_end_time: '2017-01-01' # all dates in any model are < this date

          update_window: '3 month' # how frequently to retrain models

          train_example_frequency: '1 d' # time between rows for same entity in train matrix
          train_durations: ['1 y'] # length of time included in a train matrix
          train_label_windows: ['1 month'] # time period across which outcomes are labeled in train matrices

          test_example_frequency: '1 d' # time between rows for same entity in test matrix
          test_durations: ['1 d'] # length of time included in a test matrix
          test_label_windows: ['3 month'] # time period across which outcomes are labeled in test matrices`
```

@rayidghani could you add your suggestions as a comment in this issue  ?

@shaycrk any suggestion?
