### ISSUE TITLE
Precision calculation is bogus

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#223]
precision calculation is currently taking predictions for several as of dates,  and calculating precision across all of them together, resulting in bogus results. need to look at how to do it for each as of date separately and then aggregate or something more reasonable.

**Comment by thcrock** [comment]
Not actionable as written. Closing, can reopen with more details if needed.

**Comment by nanounanue** [comment]
Given the following temporal configuration:

```yaml
temporal_config:
    feature_start_time: '2010-01-04'
    feature_end_time: '2019-01-01'
    label_start_time: '2015-02-01'
    label_end_time: '2019-01-01'

    model_update_frequency: '1y'
    training_label_timespans: ['1month']
    training_as_of_date_frequencies: '1month'

    test_durations: '1y'
    test_label_timespans: ['1month']
    test_as_of_date_frequencies: '1month'
```

Resulting in the following temporal configuration:

![inspections_baselinepng](https://user-images.githubusercontent.com/494528/52363163-b87f5100-2a07-11e9-9f11-da22eb9c6ac5.png)

As you can see, we will realize *12* different predictions in the test using the train model.

Should we get 12 different metric calculations? An array? Just the total one?
