### ISSUE TITLE
Unify sintax in scoring section in the configuration file

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#407]
Currently is:

```
scoring:
    sort_seed: 5
    metric_groups:
        -
          metrics: [precision@, recall@]
          thresholds:
            percentiles: [5.0, 10.0]
            top_n: [5, 10, 25]

    training_metric_groups:
      -
        metrics: [accuracy]
      -
        metrics: [precision@, recall@]
        thresholds:
          percentiles: [5.0, 10.0]
          top_n: [5, 10, 25]
```

It should be better to rename the first `metric_groups` to `testing_metric_groups` for consistency, i.e.

```
scoring:
    sort_seed: 5
    testing_metric_groups:
        -
          metrics: [precision@, recall@]
          thresholds:
            percentiles: [5.0, 10.0]
            top_n: [5, 10, 25]

    training_metric_groups:
      -
        metrics: [accuracy]
      -
        metrics: [precision@, recall@]
        thresholds:
          percentiles: [5.0, 10.0]
          top_n: [5, 10, 25]
```
