### ISSUE TITLE
Create feature recipe book entry for "events per decade"

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#475]
This might work:

```
categoricals:
    -
        column:
            booking_decade: "substring(start_date from 1 for 3)"
        imputation:
            sum:
                type: 'zero_noflag'
        choices: "select distinct substring(start_date from 1 for 3) from bookings"
        metrics:
            - 'sum'
```
